name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - py: "3.5"
            os: ubuntu-20.04
          - py: "3.5"
            os: macos-12
          - py: "3.4"
            os: windows-2019
            installer: easy_install
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python ${{ matrix.py }} for test
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
        env:
          PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
      - name: Install dependencies
        run: |
          ${{ matrix.installer || 'pip install' }} nose
      - name: Run tests
        run: |
          nosetests -v --with-doctest
